### ISSUE TITLE
Wrong tag/version

### ISSUE THREAD

**Issue by A----** [CartoDB/cartodb.js-bower#1]
The tagged version is not the right one.

For instance, on the 3.15.9 tag, it's still the 3.15.8 (see https://github.com/CartoDB/cartodb.js-bower/blob/3.15.9/cartodb.core.uncompressed.js )

The right commit to be tagged should be the actual master ( https://github.com/CartoDB/cartodb.js-bower/commit/a6e62aecc1139a22f338ebfcb37da9ae34c09e99 ).

Bower uses git tags as version (not what's in `bower.json`). If you `bower install` this package, it'll tell you it installed the 3.15.9 while you'll have the 3.15.8 in your `bower_components` folder.

Cheers!

**Comment by matallo** [comment]
hi @A----

I tagged a new version of cartodb.js, it should point to `3.15.10` in both cartodb.js and this repo, thanks for reporting!

https://github.com/CartoDB/cartodb.js-bower/releases/tag/3.15.10
